FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Copy app source
COPY . .

EXPOSE 3000

# Start the app
CMD ["npm", "start"]
